#!/bin/sh
CONFLIST=".csh .cshrc .gitconfig .muttrc .screenrc .ssh/authorized_keys .vim .vimrc .zsh .zshrc .erlang .pythonstartup .tmux.conf bin/ssh-auth-sock"
PLISTFILE="${PWD}/plist"
# Use $HOME/$REPO instead of $PWD, so this works even if $HOME is a symlink
REPO=${PWD##*/} # basename(1) equivalent, for wroking on iPad

Usage() {
    echo "Usage: $0 <action>"
    echo "action: (i)install/(u)ninstall"
}

BackupExistingConf() {
    if [ -e "$1" -a ! -L "$1" ]; then
	echo "Backingi up regular file: $1 -> $1.bak"
        mv -f "$1" "$1.bak"
    fi
}

ProvisionInstallDirectory() {
    for conf in ${CONFLIST}; do
        if [ "${conf##*/}" != "${conf}" -a ! -e "${HOME}/${conf%/*}" ]; then # link installed into a dir
            echo "Pre-provisioning directory: ${HOME}/${conf%/*}"
            mkdir -p "${HOME}/${conf%/*}"
	fi
    done
}

if [ -z "$1" ]; then
    Usage
    exit
fi

case $1 in
[Ii]|[Ii][Nn][Ss][Tt][Aa][Ll][Ll])
    # uninstall first
    $0 uninstall

    # provision install dir first
    ProvisionInstallDirectory

    # install them
    for link in ${CONFLIST}; do
        # be sure to backup
	BackupExistingConf "${HOME}/${link}"

	echo "Installing link: ${HOME}/${link} -> ${HOME}/${REPO}/${link}"
	ln -sfn "${HOME}/${REPO}/${link}" "${HOME}/${link}"
	echo ${HOME}/${link} >> ${PLISTFILE}
    done
    ;;
[Uu]|[Uu][Nn][Ii][Nn][Ss][Tt][Aa][Ll][Ll])
    if [ -f ${PLISTFILE} ]; then
        for link in `cat ${PLISTFILE}`; do
            echo "Removing: ${link}"
            unlink ${link}
        done

        rm -f ${PLISTFILE}
    fi
    ;;
*)
    echo "Unsupported operation: $1"
    Usage
    echo "Exiting..."
    exit
    ;;
esac
